site_name: WallGoCollision
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
markdown_extensions:
  - pymdownx.arithmatex:
    generic: true
  - markdown_include.include:
    base_path: ./docs
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
