#ifndef ENVIRONMENTMACROS_H_
#define ENVIRONMENTMACROS_H_

#include "exports_generated.h" // Generated by CMake, shared lib export/import defs

#define WALLGO_API WALLGOCOLLISION_EXPORT

// Stuff that only works for C++20 and newer. For example: std::sin, std::cos were not constexpr until C++20 
#if __cplusplus >= 202002L
	#define WG_CONSTEXPR20 constexpr
#else 
	#define WG_CONSTEXPR20
#endif

#ifdef NDEBUG
    #define WG_DEBUG 0
#else
    // Is debug build
    #define WG_DEBUG 1
#endif

#if WITH_OMP
    #include <omp.h>
#endif

#endif // header guard