name: Build Wheels

on:
  push:
    branches:
      # temp
      - DistributeBinaries

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  name: Build wheel for {{ matrix.os }}, CPython${{ matrix.python }}
  runs-on: ${{ matrix.os }}

  strategy:
    # If true, Github will cancel all other jobs in the matrix if any of them fails
    fail-fast: false
    matrix:
      include:
        - os: ubuntu-latest
          python: [3.10, 3.11, 3.12]
        
        # MacOS x86_64
        #- os: macos-13
        #  python: [3.10, 3.11, 3.12]

        # MacOS ARM64
        #- os: macos-14
        #  python: [3.10, 3.11, 3.12]

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Conan
      run: pip install conan=2.8.1

    - name: Cache Conan dependencies
      id: cache-conan
      uses: actions/cache@v4
      with:
        path: $(conan config home)
        key: ${{ runner.os }}-conan2-${{ hashFiles('**/conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan2-

      # No need to create new Conan profile if we have cache
      - if ${{steps.cache-conan.outputs.cache-hit != 'true'}}
        name: Create new Conan profile
        run: conan profile detect

      - name: Install dependencies with Conan
        run: conan install . --build=missing

