name: Build sdist

on:
  push:
    branches:
      # temp
      - BuildWheels

jobs:
  build-sdist:
    name: Build sdist (.tar.gz)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch everything to ensure we get tags
          fetch-depth: 0

      - name: Install build
        run: pip install build
      
      - name: Build sdist (.tar.gz)
        run: python -m build --sdist --verbose

      - name: Upload sdist (.tar.gz)
        uses: actions/upload-artifact@v4
        with:
          name: wallgocollision-${{ github.ref_name }}.tar.gz
          path: ./dist/*.whl