# This workflow makes a source distribution, downloads wheels built in the Build Wheels workflow and uploads to PyPI.
# Does nothing if the wheel builder failed

name: Publish to PyPI

on:
  workflow_dispatch:

jobs:

  # Source distribution
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  publish_to_TestPyPI:
    needs: make_sdist
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Download built wheels
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: wheels.yml
        branch: main
        # Must put everything to dist/ for the pypa publish action to work 
        path: dist
        search_artifacts: true
        allow_forks: false

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

