name: WallGoCollision build and Python tests

permissions:
  pull-requests: read

on:
  push:
    branches:
    # temp
    - BuildWheels

jobs:
  publish-to-testpypi:
    runs-on: ubuntu-latest

    name: Publish built wheels to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/WallGoCollision

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the wheels
        uses: actions/download-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

      - name: Download the sdist
        uses: actions/download-artifact@v4
        with:
          name: wallgocollision-${{ github.ref_name }}.tar.gz
          path: ./dist/*.whl

      - name: Publish WallGoCollision to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/