name: Publish to TestPyPi

permissions:
  pull-requests: read
  actions: read

on:
  workflow_run:  # This only works if the workflow is on the default branch
    workflows: [Build Wheels]
    types: [completed]
    branches: [BuildWheels]
  push:
    branches: [BuildWheels]

jobs:
  build-sdist:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build sdist (.tar.gz)
    # Build a tar.gz of the package with standard metadata
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Fetch everything to ensure we get tags
        fetch-depth: 0

    - name: Install build
      run: pip install build
        
    - name: Build sdist (.tar.gz)
      run: python -m build --sdist --verbose

    - name: Upload sdist (.tar.gz)
      uses: actions/upload-artifact@v4
      with:
        name: wallgocollision-${{ github.ref_name }}.tar.gz
        path: ./dist/*.tar.gz

  publish-to-testpypi:
    runs-on: ubuntu-latest
    name: Publish built wheels to TestPyPI
    needs:
      - build-sdist

    environment:
      name: testpypi
      url: https://test.pypi.org/p/WallGoCollision

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the wheels
      uses: actions/download-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

    - name: Move wheels
      run: |
        mkdir -p dist
        mv ./wheelhouse/*.whl dist 

    - name: Download the sdist
      uses: actions/download-artifact@v4
      with:
        name: wallgocollision-${{ github.ref_name }}.tar.gz
        path: ./dist/*.tar.gz

    - name: Publish WallGoCollision to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/